// Generated by Skyramp v1.3.29 on 2026-06-25 19:00:12.126591756 +0000 UTC m=+235.230820585
// Command: skyramp generate contract rest http://localhost:3000/api/v1/misc/health \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_get_misc_health_public.spec.ts \
// 		--output-dir /home/runner/work/gitea/gitea/tests/e2e \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

// contract test for /api/v1/misc/health GET
test('testHealthGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const healthGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/misc/health",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(healthGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(healthGetResponse, "status"), 'status').toBe("ok");
    expect(getResponseValue(healthGetResponse, "uptime_seconds"), 'uptime_seconds').toBeGreaterThanOrEqual(0);
});
