// Generated by Skyramp v1.3.29 on 2026-06-25 19:00:30.233670958 +0000 UTC m=+253.337899787
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output misc_health_liveness_integration_test.spec.ts \
// 		--output-dir /home/runner/work/gitea/gitea/tests/e2e \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/gitea/gitea/tests/e2e/scenario_misc_health_liveness.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let healthGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/api/v1/misc/health",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(healthGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(healthGetResponse, "status"), 'status').toBe("ok");
    expect(getValue(healthGetResponse, "uptime_seconds"), 'uptime_seconds').toBeGreaterThanOrEqual(0);
});

